
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'CounterSection': typeof import("../components/Home/counterSection.vue")['default']
    'OurSol': typeof import("../components/Home/ourSol.vue")['default']
    'SingUp': typeof import("../components/Home/singUp.vue")['default']
    'Calc': typeof import("../components/Zakah/calc.vue")['default']
    'CalcHeader': typeof import("../components/Zakah/calcHeader.vue")['default']
    'OurStratgy': typeof import("../components/about/ourStratgy.vue")['default']
    'OurValues': typeof import("../components/about/ourValues.vue")['default']
    'Paper': typeof import("../components/about/paper.vue")['default']
    'Program': typeof import("../components/about/program.vue")['default']
    'VisMis': typeof import("../components/about/visMis.vue")['default']
    'Slide1': typeof import("../components/awards/slide1.vue")['default']
    'Slide2': typeof import("../components/awards/slide2.vue")['default']
    'Slide3': typeof import("../components/awards/slide3.vue")['default']
    'Slide4': typeof import("../components/awards/slide4.vue")['default']
    'Slider': typeof import("../components/awards/slider.vue")['default']
    'FormDonate': typeof import("../components/donate /formDonate.vue")['default']
    'Change': typeof import("../components/impact/change.vue")['default']
    'InNumber': typeof import("../components/impact/inNumber.vue")['default']
    'Student': typeof import("../components/impact/student.vue")['default']
    'Header': typeof import("../components/layout/Header.vue")['default']
    'Footerr': typeof import("../components/layout/footerr.vue")['default']
    'VolunteerForm': typeof import("../components/volunteer/volunteerForm.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyCounterSection': typeof import("../components/Home/counterSection.vue")['default']
    'LazyOurSol': typeof import("../components/Home/ourSol.vue")['default']
    'LazySingUp': typeof import("../components/Home/singUp.vue")['default']
    'LazyCalc': typeof import("../components/Zakah/calc.vue")['default']
    'LazyCalcHeader': typeof import("../components/Zakah/calcHeader.vue")['default']
    'LazyOurStratgy': typeof import("../components/about/ourStratgy.vue")['default']
    'LazyOurValues': typeof import("../components/about/ourValues.vue")['default']
    'LazyPaper': typeof import("../components/about/paper.vue")['default']
    'LazyProgram': typeof import("../components/about/program.vue")['default']
    'LazyVisMis': typeof import("../components/about/visMis.vue")['default']
    'LazySlide1': typeof import("../components/awards/slide1.vue")['default']
    'LazySlide2': typeof import("../components/awards/slide2.vue")['default']
    'LazySlide3': typeof import("../components/awards/slide3.vue")['default']
    'LazySlide4': typeof import("../components/awards/slide4.vue")['default']
    'LazySlider': typeof import("../components/awards/slider.vue")['default']
    'LazyFormDonate': typeof import("../components/donate /formDonate.vue")['default']
    'LazyChange': typeof import("../components/impact/change.vue")['default']
    'LazyInNumber': typeof import("../components/impact/inNumber.vue")['default']
    'LazyStudent': typeof import("../components/impact/student.vue")['default']
    'LazyHeader': typeof import("../components/layout/Header.vue")['default']
    'LazyFooterr': typeof import("../components/layout/footerr.vue")['default']
    'LazyVolunteerForm': typeof import("../components/volunteer/volunteerForm.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CounterSection: typeof import("../components/Home/counterSection.vue")['default']
export const OurSol: typeof import("../components/Home/ourSol.vue")['default']
export const SingUp: typeof import("../components/Home/singUp.vue")['default']
export const Calc: typeof import("../components/Zakah/calc.vue")['default']
export const CalcHeader: typeof import("../components/Zakah/calcHeader.vue")['default']
export const OurStratgy: typeof import("../components/about/ourStratgy.vue")['default']
export const OurValues: typeof import("../components/about/ourValues.vue")['default']
export const Paper: typeof import("../components/about/paper.vue")['default']
export const Program: typeof import("../components/about/program.vue")['default']
export const VisMis: typeof import("../components/about/visMis.vue")['default']
export const Slide1: typeof import("../components/awards/slide1.vue")['default']
export const Slide2: typeof import("../components/awards/slide2.vue")['default']
export const Slide3: typeof import("../components/awards/slide3.vue")['default']
export const Slide4: typeof import("../components/awards/slide4.vue")['default']
export const Slider: typeof import("../components/awards/slider.vue")['default']
export const FormDonate: typeof import("../components/donate /formDonate.vue")['default']
export const Change: typeof import("../components/impact/change.vue")['default']
export const InNumber: typeof import("../components/impact/inNumber.vue")['default']
export const Student: typeof import("../components/impact/student.vue")['default']
export const Header: typeof import("../components/layout/Header.vue")['default']
export const Footerr: typeof import("../components/layout/footerr.vue")['default']
export const VolunteerForm: typeof import("../components/volunteer/volunteerForm.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyCounterSection: typeof import("../components/Home/counterSection.vue")['default']
export const LazyOurSol: typeof import("../components/Home/ourSol.vue")['default']
export const LazySingUp: typeof import("../components/Home/singUp.vue")['default']
export const LazyCalc: typeof import("../components/Zakah/calc.vue")['default']
export const LazyCalcHeader: typeof import("../components/Zakah/calcHeader.vue")['default']
export const LazyOurStratgy: typeof import("../components/about/ourStratgy.vue")['default']
export const LazyOurValues: typeof import("../components/about/ourValues.vue")['default']
export const LazyPaper: typeof import("../components/about/paper.vue")['default']
export const LazyProgram: typeof import("../components/about/program.vue")['default']
export const LazyVisMis: typeof import("../components/about/visMis.vue")['default']
export const LazySlide1: typeof import("../components/awards/slide1.vue")['default']
export const LazySlide2: typeof import("../components/awards/slide2.vue")['default']
export const LazySlide3: typeof import("../components/awards/slide3.vue")['default']
export const LazySlide4: typeof import("../components/awards/slide4.vue")['default']
export const LazySlider: typeof import("../components/awards/slider.vue")['default']
export const LazyFormDonate: typeof import("../components/donate /formDonate.vue")['default']
export const LazyChange: typeof import("../components/impact/change.vue")['default']
export const LazyInNumber: typeof import("../components/impact/inNumber.vue")['default']
export const LazyStudent: typeof import("../components/impact/student.vue")['default']
export const LazyHeader: typeof import("../components/layout/Header.vue")['default']
export const LazyFooterr: typeof import("../components/layout/footerr.vue")['default']
export const LazyVolunteerForm: typeof import("../components/volunteer/volunteerForm.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
