// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/9/2024, 6:55:59 PM
const configMerger = require("/Users/nadarayan/Desktop/net3allem/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/nadarayan/Desktop/net3allem/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nadarayan/Desktop/net3allem/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nadarayan/Desktop/net3allem/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nadarayan/Desktop/net3allem/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nadarayan/Desktop/net3allem/plugins/**/*.{js,ts,mjs}","/Users/nadarayan/Desktop/net3allem/composables/**/*.{js,ts,mjs}","/Users/nadarayan/Desktop/net3allem/utils/**/*.{js,ts,mjs}","/Users/nadarayan/Desktop/net3allem/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/nadarayan/Desktop/net3allem/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/nadarayan/Desktop/net3allem/app.config.{js,ts,mjs}"] } }));

module.exports = config
